### ISSUE TITLE
Not working with React?

### ISSUE THREAD

**Issue by NayamAmarshe** [lacymorrow/movie-art#2]
I'd like to use this module but React throws an error:
![image](https://user-images.githubusercontent.com/25067102/113831454-42243800-97a5-11eb-82ee-06f8ed496a42.png)

**Comment by lacymorrow** [comment]
How are you requiring the library? (sorry for the late response)

**Comment by NayamAmarshe** [comment]
> How are you requiring the library? (sorry for the late response)

I have no idea, sorry😅 It's been more than a year, it was just a side project I was making so nothing too critical :)

**Comment by lacymorrow** [comment]
Fixed in v3: https://github.com/lacymorrow/movie-art/releases/tag/v3.0.0
